export const SET_BLOG_POSTS = 'setBlogPosts'
export const SET_CONNECTIONS = 'setConnections'
export const TOGGLE_MENU = 'toggleMenu'
export const IS_MOBILE = 'isMobile'
export const SET_SITE_INFO = 'setSiteInfo'
