site_url: https://dotyk.netlify.app/
logo_url: https://dotyk.netlify.app/icon.png

# publish_mode: editorial_workflow
backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

# Docs: https://www.netlifycms.org/docs/configuration-options/#collections
collections:
  - label: 'Site settings'
    name: 'site'
    files:
      - label: 'Info'
        name: 'info'
        file: 'assets/content/site/info.json'
        format: 'json'
        editor:
          preview: false
        fields:
          - { label: Site Name, name: sitename, widget: string, hint: 'This is used for the site title' }
          - {
              label: Site Description,
              name: sitedescription,
              widget: string,
              hint: 'This is used as descriptive text for links that link to this site',
            }
          - {
              label: Site Language,
              name: sitelang,
              widget: string,
              pattern: ['^[a-z]{2}([-])?([A-Za-z]{2})?$', 'Must match "xx" or "xx-XX" syntax (ex. "en" or "sv-SE")'],
            }
          - {
              label: 'email',
              name: 'email',
              widget: 'string',
            }
          - {
              label: 'instagram',
              name: 'instagram',
              widget: 'string',
            }
          - {
              label: 'Contribute Form',
              name: 'contribute_form',
              widget: 'string',
            }
          # - { label: Site Email, name: siteemail, widget: string, required: false }
  - label: 'About'
    name: 'about'
    files:
      - label: 'About text'
        name: 'abouttext'
        file: 'assets/content/site/about.json'
        format: 'json'
        editor:
        preview: false
        fields:
          - {
              label: 'About (English)',
              name: 'about_en',
              widget: 'markdown',
              hint: 'This is used as descriptive text for links that link to this site',
            }
          - {
              label: 'About (Belarusian)',
              name: 'about_be',
              widget: 'markdown',
              hint: 'This is used as descriptive text for links that link to this site',
            }
          # - { label: Site Email, name: siteemail, widget: string, required: false }
  - name: 'connections'
    label: 'Connections'
    identifier_field: 'name_en'
    folder: 'assets/content/connections'
    create: true
    format: 'json'
    slug: '{{slug}}'
    fields:
      - { name: 'node_id', label: 'Node Id', widget: 'string' , required: true, pattern: ['.\S+\w{1,32}\S{1,}', "No space or special characters are allowed."], hint: 'write the name of the connection with no special character or spaces.',} 
      - { label: 'Name (en)',  name: 'name_en', widget: 'string' , required: true} 
      - { label: 'Name (be)',  name: 'name_be', widget: 'string' , required: false , default: ''} 
      - { label: 'Node Type',  name: 'node_type', widget: 'string' , required: false, default: ''} 
      - { 
          name: 'connections',
          label: 'Connections',
          widget: 'relation',
          multiple: true,
          max: 99,
          collection: 'connections',
          search_fields: ['node_id'],
          value_field: 'node_id',
          display_fields: ["node_id"],
          required: false,
          default: []
        } 
      - { name: 'tags', label: 'tags', widget: 'list', default: [], required: false } 
      - { name: 'type', label: 'type', widget: 'string', required: false, default: '' } 
      - { name: 'Content (en)', label: 'content_en', widget: 'markdown' , required: false, default: ''} 
      - { name: 'Content (be)', label: 'content_be', widget: 'markdown' , required: false, default: ''} 
  - name: 'blog'
    label: 'Blog'
    folder: 'assets/content/blog'
    identifier_field: 'title_en'
    create: true
    format: 'json'
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    fields:
      - { label: 'Title (en)', name: 'title_en', widget: 'string' }
      - { label: 'Author (en)', name: 'author_en', widget: 'string' }
      - { label: 'Body (en)', name: 'body_en', widget: 'markdown' }
      - { label: 'Short Description (en)', name: 'description_en', widget: 'markdown',  hint: 'Text that will be displayed in the blog menu. If not present, a preview of the body content will appear.' }
      - { label: 'Title (be)', name: 'title_be', widget: 'string' }
      - { label: 'Author (be)', name: 'author_be', widget: 'string' }
      - { label: 'Body (be)', name: 'body_be', widget: 'markdown' }
      - { label: 'Short Description (be)', name: 'description_be', widget: 'markdown',  hint: 'Text that will be displayed in the blog menu. If not present, a preview of the body content will appear.' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Highlight', name: 'highlight', widget: 'boolean', hint: 'a highlighted blog post will appear wider in the blog screen.' }